 
const admin = 'admin';

const routes = {
    home: "/",
    nam: "/nam",
    nu: "/nu",
    treem: "/treem", 
    login: "/login",
    test: "/test",
    searchProduct: `/search`,
    infoProduct: "/infoProduct",
    cart: "/cart",
    cart_test: "/cart_test",
    payment: "/payment",
    addProduct: "/admin/addProduct",
    paymentResult: "/paymentResult",
    myOrder: "/myOrder",
    manageOrder: "/admin/manageOrder",
    manageProduct: "/admin/manageProduct",
    updateProduct: "/admin/updateProduct",
    updateProduct2: "/admin/updateProduct2",
    infoAccount: "/infoAccount",
    printOrder: "/admin/printOrder",
    searchOrder: "/admin/searchOrder",
    searchProductAdmin: "/admin/searchProductAdmin",
    adminLogin: "/admin/AdminLogin",
    manageAccountStaff: "/admin/ManageAccountStaff",
    manageAccountCustomer: "/admin/manageAccountCustomer",
    addVoucher: "/admin/addVoucher",
    manageVoucher: "/admin/manageVoucher",
    searchVoucher: "/admin/SearchVoucher",
    reviewProduct: "/reviewProduct",
    statistic: "/admin/Statistic",
}
export default routes;